### ISSUE TITLE
link to a forum search in a "troubleshooting installation" section

### ISSUE THREAD

**Issue by gregcaporaso** [caporaso-lab/using-qiime2#18]
we'll do this here, instead of in docs (so closing https://github.com/qiime2/docs/issues/560 in favor of this issue). 

I think the best way for us to do this would be to link to an `install` (or similar) tag that we use on the forum, so we have some level of curation over what shows up when users click this link.

**Comment by lizgehret** [comment]
Hey @gregcaporaso - the `install-faqs` tag has been created (staff-only for adding/removing the tag from posts) - here's the URL for that tag: https://forum.qiime2.org/tag/install-faqs

Right now it's empty but I'm going to work on slowly adding old posts to this, and I've asked the mod team to add posts that seem useful as well (moving forward).

**Comment by gregcaporaso** [comment]
Thanks for working on this @lizgehret - the new tag seems great. 

One thing we haven't figured out yet is where distribution-specific installation instructions are going to live, but I would like us to sort this out in this release cycle. Once we make that decision then we're ready to link this from that spot.

**Comment by gregcaporaso** [comment]
Though I guess in any case we should have a References > Installing QIIME 2 document in here. That could currently link to the install page in docs.qiime2.org, and include this link in a troubleshooting section. Feel free to add that now, or we can hold off and discuss.

**Comment by lizgehret** [comment]
I think having that under a References section makes sense to me - let's discuss specifics during our meeting tomorrow, and then I can get started on that!

**Comment by lizgehret** [comment]
closed by https://github.com/caporaso-lab/developing-with-qiime2/pull/136
